package:
  name: mltoolkit
  version: "0.1.0"

source:
  fn: mltoolkit-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mltoolkit/mltoolkit-0.1.0.tar.gz
  md5: b3343bd28059b4b27e69b56050714d3b

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mltoolkit = mltoolkit:main
    #
    # Would create an entry point called mltoolkit that calls mltoolkit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scikit-learn
    - argparse
    - multiprocessing
    - hyperopt
    - bson
    - pymongo
    - networkx

  run:
    - python
    - numpy
    - scikit-learn
    - argparse
    - multiprocessing
    - hyperopt
    - bson
    - pymongo
    - networkx

test:
  # Python imports
  imports:
    - mltoolkit
    - mltoolkit.examples
    - mltoolkit.test
    - mltoolkit.tuning

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://pypi.python.org/pypi/mltoolkit
  license: new BSD
  summary: 'Some modelling tools'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
